#
# Copyright (c) 2021 Tobias Thummerer, Lars Mikelsons, Josef Kircher
# Licensed under the MIT license. See LICENSE file in the project root for details.
#

"""

    FMU 

The abstract type for FMUs (FMI 2 & 3).
"""
abstract type FMU end
export FMU

"""

    FMUSolution

The abstract type for a solution generated by simulating an FMU (FMI 2 & 3).
"""
abstract type FMUSolution end
export FMUSolution

"""

    FMUExecutionConfiguration

The abstract type for the configuration used to simulate (execute) an FMU (FMI 2 & 3).
"""
abstract type FMUExecutionConfiguration end
export FMUExecutionConfiguration

"""

    FMUEvent

The abstract type for an event triggered by a FMU (FMI 2 & 3).
"""
abstract type FMUEvent end
export FMUEvent